export const riskActionsByFactor = {
  'Gênero': { nome: 'Gênero', acao: 'Ajustar campanhas de marketing para segmentação de gênero específica.' },
  'Gênero Masculino': { nome: 'Gênero Masculino', acao: 'Ajustar campanhas de marketing para segmentação de gênero masculino.' },
  'Gênero Feminino': { nome: 'Gênero Feminino', acao: 'Ajustar campanhas de marketing para segmentação de gênero feminino.' },
  Idade: { nome: 'Idade', acao: 'Oferecer planos adequados à faixa etária (ex: Universitário ou Família).' },
  'País': { nome: 'País', acao: 'Localizar conteúdo e ajustar preços conforme a moeda e região.' },
  'País França': { nome: 'País França', acao: 'Localizar conteúdo e ajustar preços conforme a moeda e região francesa.' },
  'País Índia': { nome: 'País Índia', acao: 'Localizar conteúdo e ajustar preços conforme a moeda e região indiana.' },
  'Tipo de Assinatura': { nome: 'Tipo de Assinatura', acao: 'Sugerir upgrade para planos com mais benefícios.' },
  'Assinatura Estudante': { nome: 'Assinatura Estudante', acao: 'Apresentar planos exclusivos para estudantes e após formar, oferecer descontos no plano premium ou plano pré-pago.' },
  'Tempo de Escuta': { nome: 'Tempo de Escuta', acao: 'Enviar recomendações personalizadas para aumentar o engajamento.' },
  'Músicas por Dia': { nome: 'Músicas por Dia', acao: 'Notificações push com novas playlists baseadas no comportamento diário.' },
  'Taxa de Pulagem': { nome: 'Taxa de Pulagem', acao: 'Recalibrar algoritmo de recomendação para reduzir pulos.' },
  'Tipo de Dispositivo': { nome: 'Tipo de Dispositivo', acao: 'Otimizar interface e bugs específicos para o hardware do usuário.' },
  'Anúncios por Semana': { nome: 'Anúncios por Semana', acao: 'Oferecer teste Premium para aliviar interrupções de áudio. Após o teste, oferecer plano premium ou plano pré-pago.' },
  'Uso Offline': { nome: 'Uso Offline', acao: 'Destacar funcionalidades de download em campanhas educacionais.' },
  'Músicas por Minuto': { nome: 'Músicas por Minuto', acao: 'Sugerir playlists focadas em ritmos específicos.' },
  'Intensidade de Anúncios': { nome: 'Intensidade de Anúncios', acao: 'Reduzir carga de anúncios temporariamente para reter o usuário. Ofertar planos sem anúncios.' },
  'Índice de Frustração': { nome: 'Índice de Frustração', acao: 'Enviar pesquisa de satisfação com cupom de desconto imediato.' },
  'Usuário Intenso (Heavy)': { nome: 'Usuário Intenso (Heavy)', acao: 'Oferecer programa de recompensas e acesso antecipado a recursos.' },
  'Premium sem Offline': { nome: 'Premium sem Offline', acao: 'Sugerir plano Premium completo com suporte a downloads.' },
}
